#!/usr/bin/bash

#dirs:=$(shell find . -maxdepth 1 -type d)
#dirs:=$(basename $(patsubst ./%,%,$(dirs)))
#SUBDIRS:=$(dirs)
#
#TARGET = $(notdir $(CURDIR)) 
#
#SRCS:=$(wildcard *.c)
#OBJS:=$(SRCS:%c=%o)
#DEPENDS:=$(SRC:%c=%d)
#
#
#$(TARGET):$(OBJS)
#	@echo compiling $@ from $^
#	$(MAKE) $(CFLAGS) $(LDFLAGS) $^  -o $@
#
#
#
#$(OBJS):%.o : %.c
#	@echo compiling $@ from $^
#	$(CC) $(CFLAGS) $< -o $@ $(INC_PATH)
#
#
#
#fse
#
#
#
#
#
#c1:	
#	gcc -o chapter1.exe chapter1.c
#
#	
#c2:	
#	gcc -o chapter2.exe chapter2.c
#	
#c3:	
#	gcc -o chapter3.exe chapter3.c
#
#	
#c4:	
#	gcc -o chapter4.exe chapter4.c	
#	
#	
#	
#c5:	
#	gcc -o chapter5.exe chapter5.c
#	
#
#subdirs:$(SUBDIRS)
#	@for dir in $(SUBDIRS); \
#	do $(MAKE) -C $$dir all || exit 1; \
#	done
#
#	
#clean:
#	rm -r *.exe *.o
#	
#	
#clean_all:
#	@for dir in $(SUBDIRS); \
#	do $(MAKE) -C $$dir clean || exit 1; \
#	done
	
	
all:	
	make -C $$dir  